version: '3.1'

services:
  authapi:
    env_file:
      - .env
    build:
      context: ./
    ports:
      - ${SIMPLEAUTH_PORT}:${SIMPLEAUTH_PORT}
    sysctls:
      net.core.somaxconn: 8128
    restart: ${RESTART:-unless-stopped}
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: ${RESTART:-unless-stopped}
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=authapi
      - MONGO_INITDB_DATABASE=simpleauth
    volumes:
      - mongodb:/data/mongodb
  mongo-express:
    image: mongo-express
    restart: ${RESTART:-unless-stopped}
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: authapi
      ME_CONFIG_MONGODB_URL: mongodb://root:authapi@mongo:27017/
volumes:
  mongodb: {}


