package token

import (
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/sha256"

	"go.k7z7z.cc/x/encoding/base64url"
)

// AppID represents an application ID that is used to generate and verify
// tokens. It is a wrapper around a byte slice that provides additional
// methods for setting and getting the application ID.
type AppID []byte

// String method returns the application ID as a string. If the application
// ID is nil, an empty string is returned. It internally calls the Bytes
// method to get the application ID as a byte slice and converts it to a
// string.
func (id *AppID) String() string {
	return string(id.Bytes())
}

// SetString method sets the application ID from a string. If the application
// ID is nil, a new application ID is created. If the string is empty, the
// application ID is not set. It internally calls the SetBytes method to set
// the application ID from a byte slice.
func (id *AppID) SetString(data string) *AppID {
	return id.SetBytes([]byte(data))
}

// Bytes method returns the application ID as a byte slice.
func (id *AppID) Bytes() []byte {
	if id == nil {
		return nil
	}
	return []byte(*id)
}

// SetBytes method sets the application ID from a byte slice. If the
// application ID is nil, a new application ID is created. If the byte slice
// is empty, the application ID is not set. It internally calls the Unmarshal
// method of the App to check that the application ID is valid before setting
// the application ID from the byte slice. If the resulting application is not
// valid, the application ID is not set and nil is returned.
func (id *AppID) SetBytes(data []byte) *AppID {
	// check if the application ID is valid
	if err := new(App).Unmarshal(data).Valid(nil); err != nil {
		return nil
	}
	// if no application ID is provided, create a new one
	if id == nil {
		id = new(AppID)
	}
	// set the application ID
	*id = data
	return id
}

// PrivKey method returns the private key for the application ID. If the
// application ID is nil or the secret is invalid, nil is returned. It
// internally calls the Bytes method to get the application ID as a byte
// slice and uses it to generate the private key. The private key is
// generated by hashing the application ID with the secret and using the
// resulting hash as the seed for an ed25519 private key.
func (id *AppID) PrivKey(secret Secret) ed25519.PrivateKey {
	if !secret.Valid() {
		return nil
	}
	if id == nil {
		return nil
	}
	bID := id.Bytes()
	if len(bID) == 0 {
		return nil
	}
	hFn := hmac.New(sha256.New, secret.Bytes())
	hFn.Write(bID)
	hID := hFn.Sum(nil)
	return ed25519.NewKeyFromSeed(hID[:32])
}

// Sign method returns the signature of the message for the application ID.
// If the application ID is nil, the message is empty, or the secret is
// invalid, nil is returned. It internally calls the PrivKey method to get
// the private key for the application ID and uses it to sign the message.
// The message is signed by appending a nonce to it and hashing the result
// with the private key. The signature is then encoded to base64 before
// being returned to be used as a part of the token, keeping it as short as
// possible.
func (id *AppID) Sign(secret Secret, msg []byte) []byte {
	// check if the application ID is valid or the message is empty
	if id == nil || len(msg) == 0 {
		return nil
	}
	// get the private key for the application ID and the secret
	privKey := id.PrivKey(secret)
	if len(privKey) == 0 {
		return nil
	}
	// append the message with a nonce and hash it with the private key
	data := append(msg, hedgedNonce(privKey[:], msg)...)
	// sign the data with the private key
	rawSign := ed25519.Sign(privKey, data[:])
	// encode the signature to base64 and return it
	return base64url.RawEncode(rawSign)
}

// Verify method returns true if the signature of the message is valid for
// the application ID. If the application ID is nil, the message is empty,
// the signature is empty, or the secret is invalid, false is returned. It
// internally calls the PrivKey method to get the private key for the
// application ID and uses it to verify the signature. The message is
// verified by appending a nonce to it and hashing the result with the
// public key. The signature is then decoded from base64 and verified with
// the public key to ensure that it was signed by the private key.
func (id *AppID) Verify(secret Secret, msg, sig []byte) bool {
	// check if the application ID is valid or the message and signature are
	// not empty
	if id == nil || len(msg) == 0 || len(sig) == 0 {
		return false
	}
	// get the private key for the application ID and the secret
	privKey := id.PrivKey(secret)
	if privKey == nil {
		return false
	}
	// decode sign from base64
	rawSign, err := base64url.RawDecode(sig)
	if err != nil {
		return false
	}
	// recover the data with the nonce and the message
	data := append(msg, hedgedNonce(privKey[:], msg)...)
	// verify the data with the public key
	pubKey := privKey.Public().(ed25519.PublicKey)
	return ed25519.Verify(pubKey, data, rawSign)
}

// GenerateToken method returns a token for the application ID. If the app ID
// is nil, the secret is invalid, or the email is empty, nil is returned. It
// internally calls the Message method to generate the message for the token
// and uses it to sign the message. The token is generated by hashing the
// application ID with the email and expiration time, and signing the result
// with the secret. The signature is then used to create a token with the
// expiration time and signature.
func (id *AppID) GenerateToken(secret Secret, email Email) Token {
	// check if the application ID is valid
	if id == nil {
		return nil
	}
	// get the application for the application ID
	app := new(App).SetID(id)
	if app == nil {
		return nil
	}
	// calculate the expiration time for the current app
	exp := new(Expiration).SetDuration(app.SessionDuration)
	if exp == nil {
		return nil
	}
	// get the message to sign
	msg := id.Message(email, *exp)
	// sign the message with the secret
	sig := id.Sign(secret, msg)
	// check if the signature is valid
	if len(sig) == 0 {
		return nil
	}
	// create a new token with the expiration time and signature
	return *new(Token).SetExpiration(*exp).SetSignature(sig).SetEmail(email)
}

// Message method returns the message for the application ID. If the app ID
// is nil, the email is empty, or the expiration time is invalid, nil is
// returned. It is used to generate the message for the token by hashing the
// application ID with the email and expiration time. The message is generated
// by appending the application ID with the email and expiration time, and
// hashing the result with sha256 to create a unique message for the token.
func (id *AppID) Message(email Email, exp Expiration) []byte {
	// check if the application ID is valid, the email is not empty, and the
	// expiration time is valid
	if id == nil || len(email) == 0 || !exp.Valid() {
		return nil
	}
	// hash the application ID with the email and expiration time
	hmsg := sha256.Sum256(append(append(id.Bytes(), email.Bytes()...), exp.Bytes()...))
	return hmsg[:]
}

// VerifyToken method returns true if the token is valid for the application
// ID. If the app ID is nil, the token is nil, the secret is invalid, or the
// email is empty, false is returned. It is used to verify the token by
// checking that the expiration time is valid and the signature is correct.
// The token is verified by hashing the application ID with the email and
// expiration time, and verifying the signature with the secret.
func (id *AppID) VerifyToken(token Token, secret Secret) bool {
	// check if the application ID is valid
	if id == nil {
		return false
	}
	email := token.Email()
	// check if the expiration time is valid
	exp := token.Expiration()
	if exp == nil || !exp.Valid() {
		return false
	}
	// check if the token contains a signature
	sig := token.Signature()
	if len(sig) == 0 {
		return false
	}
	// get the message to verify
	msg := id.Message(*email, *exp)
	if len(msg) == 0 {
		return false
	}
	// verify the token with the secret
	return id.Verify(secret, msg, sig)
}

// hedgedNonce function returns a nonce for the application ID. It is used to
// generate a unique nonce for the application ID by hashing the application
// ID with the message. The nonce is generated by appending the application ID
// with the message and hashing the result with sha256. It helps to prevent
// replay attacks by ensuring that the nonce is unique for each message.
func hedgedNonce(inputs ...[]byte) []byte {
	if len(inputs) == 0 || len(inputs[0]) == 0 {
		return nil
	}
	hFn := hmac.New(sha256.New, inputs[0])
	for _, in := range inputs[1:] {
		hFn.Write(in)
	}
	return hFn.Sum(nil)
}
