package token

import "bytes"

// numOfTokensParts const defines the number of parts that a Token has encoded.
// This number is used decode a encoded token into its multiple parts, or
// encode valid parts into a encoded token.
const numOfTokenParts = 3

// emptyToken is a helper var used by String() of Token struct to check if the
// a token is empty.
var emypyToken = bytes.Join(make([][]byte, numOfTokenParts), []byte{tokenSeparator})

// Signature wraps a byte slice to be used in signature operations.
type Signature []byte

// Empty method returns true if the current signature is empty (lenght 0).
func (s Signature) Empty() bool {
	return len(s) == 0
}

// Token is a type that represents a user token. It is a wrapper around a byte
// slice that provides additional methods for setting and getting the token. It
// should have 3 parts:
//   - The token expiration time (encoded).
//   - The token signature, generated by the server using the secret over the
//     expiration and the email of the user to generate the signature.
//   - The email of the user who attempts to be authenticated.
type Token []byte

// Valid method returns a boolean indicating if the current Token is valid. A
// A valid token has three valid parts:
//   - The expiration of the token.
//   - The token signature.
//   - A valid user email.
func (t *Token) Valid() bool {
	if t == nil {
		return false
	}
	_, _, _, ok := t.split()
	switch {
	case !ok:
		return false
	case t.Expiration().Empty():
		return false
	case t.Signature().Empty():
		return false
	case !t.Email().Valid():
		return false
	default:
		return true
	}
}

// String method returns the token as a string. It is useful for encoding the
// token. If the token is nil, an empty string is returned. It internally calls
// the Bytes method to get the token as a byte slice.
func (t *Token) String() string {
	if t == nil {
		return ""
	}
	if bytes.Equal(emypyToken, t.Bytes()) {
		return ""
	}
	return string(t.Bytes())
}

// SetString method sets the token from a string. It is useful for decoding the
// token. The string should be the token's expiration time and signature joined
// by the token separator. If the token is invalid, the token is not set. It
// internally calls the SetBytes method to set the token from a byte slice.
func (t *Token) SetString(data string) *Token {
	if t == nil {
		t = new(Token)
	}
	return t.SetBytes([]byte(data))
}

// Bytes method returns the token as a byte slice. It is useful for encoding
// the token. If the token is nil, nil is returned. It internally calls the
// parts method to get the token's expiration time and signature as byte
// slices. It checks that the parts are valid before returning the token
// as a byte slice.
func (t *Token) Bytes() []byte {
	// check if the token is nil
	if t == nil {
		return nil
	}
	// check if the token has valid parts
	if _, _, _, ok := t.split(); !ok {
		return nil
	}
	// return the token as a byte slice
	return *t
}

// SetBytes method sets the token from a byte slice. It is useful for
// decoding the token. The byte slice should be the token's expiration time
// and signature joined by the token separator. If the token is invalid, the
// token is not set. It internally calls the parts method to get the token's
// expiration time and signature as byte slices. It checks that the parts are
// valid before setting the token from the byte slice.
func (t *Token) SetBytes(data []byte) *Token {
	// if no token is provided, create a new one
	if t == nil {
		t = new(Token)
	}
	// generate a new token from the data
	ntoken := &Token{}
	*ntoken = data
	// check if the new token has valid parts
	if _, _, _, ok := ntoken.split(); !ok {
		return t
	}
	// set the token to the new token
	*t = data
	return t
}

// Expiration method returns the token's expiration time. It is useful for
// getting the expiration time. If the token is nil, nil is returned. It
// internally calls the parts method to get the token's expiration time and
// signature as byte slices. It checks that the expiration time is valid before
// returning it.
func (t *Token) Expiration() *Expiration {
	rawExp, _, _, ok := t.split()
	if rawExp == nil || !ok {
		return nil
	}
	return new(Expiration).Unmarshal(rawExp)
}

// SetExpiration method sets the token's expiration time. If the token is nil,
// a new token is created. If the expiration time is invalid, the token is not
// set. It internally calls the parts method to replace the token's expiration
// time with the new expiration time. It checks that the expiration time is
// valid before setting it.
func (t *Token) SetExpiration(exp Expiration) *Token {
	return t.join(
		exp.Marshal(),
		t.Signature(),
		t.Email().Marshal(),
	)
}

// Signature method returns the token's signature. If the token is nil, nil is
// returned. It internally calls the parts method to get the signature part as
// byte slices.
func (t *Token) Signature() Signature {
	_, sig, _, _ := t.split()
	if len(sig) == 0 {
		return nil
	}
	return sig
}

// SetSignature method sets the token's signature. If the token is nil, a
// new token is created. If the signature is nil, the token is not set. It
// internally calls the parts method to replace the token's signature with
// the new signature.
func (t *Token) SetSignature(sig Signature) *Token {
	return t.join(
		t.Expiration().Marshal(),
		sig,
		t.Email().Marshal(),
	)
}

func (t *Token) Email() *Email {
	_, _, rawEmail, ok := t.split()
	if len(rawEmail) == 0 || !ok {
		return nil
	}
	return new(Email).Unmarshal(rawEmail)
}

func (t *Token) SetEmail(email Email) *Token {
	return t.join(
		t.Expiration().Marshal(),
		t.Signature(),
		email.Marshal(),
	)
}

// split private method returns the token's expiration time and signature as
// byte slices. It also returns a boolean indicating if the token has valid
// parts. If the token is nil, or the parts are invalid, the parts are nil and
// the boolean is false. It splits the token by the token separator and checks
// that the result has 2 parts (expiration time and signature).
func (t *Token) split() ([]byte, []byte, []byte, bool) {
	if t == nil {
		return nil, nil, nil, false
	}
	p := bytes.Split([]byte(*t), []byte{tokenSeparator})
	if len(p) != numOfTokenParts {
		return nil, nil, nil, false
	}
	return p[0], p[1], p[2], true
}

func (t *Token) join(parts ...[]byte) *Token {
	// if no token is provided, create a new one
	if t == nil {
		t = new(Token)
	}
	if len(parts) != numOfTokenParts {
		return t
	}
	content := bytes.Join(parts, []byte{tokenSeparator})
	return t.SetBytes(content)
}
