# build
FROM golang:1.26-alpine as builder

WORKDIR /app/data
COPY . .

RUN go mod tidy
RUN go build -o /authapi ./cmd/demo/main.go

# deploy
FROM alpine:latest

EXPOSE 80

WORKDIR /
COPY --from=builder /authapi /authapi

ENTRYPOINT /authapi